language: ruby
before_install: gem install bundler -v 1.17.3
services:
  - postgresql
before_script:
  - bin/rails db:create
  - bin/rails db:migrate
script:
  - bundle exec rspec
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: mii8pAUcEPgNR07R02yiDCJI0PV96Ry8eDC+OI1gMWBbwDxY94Q3M2XvFGa8EeaUBLrHSCb/TNBysHAEX2MICSOHaOB7z2NzhMHDccGTZpbY34BM5MLPtswlYv6unsUWh4c+3SMtqMHvxQ0AaMxsmsiDUYLj7dj8ETjac38phTgkKDD+a8ZreEVI4Ts+PzhpgJBhDLkU8xi5XDUNMv9JiY+g9TotlZEFxJXJnK7VCET5B6VKZAA3l4d7EwW1BX1nXQEKVC48ZJR5XBg6LL1ZsFI/EkYzSaC1qbsHRHJmcKfF6wxUmqIMlH34q4kCB2HzGAdXTO1nGoHDNtnTEvIQEecwCph47Y1+oicr+64goQv1aH+4cxWsE1DiSJsP6DUD87Bsa4WvSsuWLK+za+5KMnx3ujKxYv8jO0AwxMkHhNwi+ROF9pL8Flu9aHZUBJ+spgnya+qNSBSUpkSuxnktdfDd9eRnSEPL8LdyBIL5OPoCEpFpZirwbcNRxsN4NRc3xP/OEiY1tmMOV/9YmdKJY/tjHWL+TGNQEYLTcJ9iA1KebfhC+PbT0qsNtmP86ZuyQoAm1qfsIOVkBzRaji+hlRazAIh02NYVW9/lSGDiXQIjs4zq5x0kfsXjX0T9Cg1NRDVOf8lN4mjay4Ek+GSZLiNFGuYusMrQII78zUe53eY=
  app: jjer
  on:
    repo: Emanuele-20/acebook-rails-template
